/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pir;

public class ArrayofVectorUInt8 extends java.util.AbstractList<VectorUInt8> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayofVectorUInt8(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayofVectorUInt8 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ArrayofVectorUInt8 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pirJNI.delete_ArrayofVectorUInt8(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayofVectorUInt8(VectorUInt8[] initialElements) {
    this();
    reserve(initialElements.length);

    for (VectorUInt8 element : initialElements) {
      add(element);
    }
  }

  public ArrayofVectorUInt8(Iterable<VectorUInt8> initialElements) {
    this();
    for (VectorUInt8 element : initialElements) {
      add(element);
    }
  }

  public VectorUInt8 get(int index) {
    return doGet(index);
  }

  public VectorUInt8 set(int index, VectorUInt8 e) {
    return doSet(index, e);
  }

  public boolean add(VectorUInt8 e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, VectorUInt8 e) {
    modCount++;
    doAdd(index, e);
  }

  public VectorUInt8 remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public ArrayofVectorUInt8() {
    this(pirJNI.new_ArrayofVectorUInt8__SWIG_0(), true);
  }

  public ArrayofVectorUInt8(ArrayofVectorUInt8 other) {
    this(pirJNI.new_ArrayofVectorUInt8__SWIG_1(ArrayofVectorUInt8.getCPtr(other), other), true);
  }

  public long capacity() {
    return pirJNI.ArrayofVectorUInt8_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    pirJNI.ArrayofVectorUInt8_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return pirJNI.ArrayofVectorUInt8_isEmpty(swigCPtr, this);
  }

  public void clear() {
    pirJNI.ArrayofVectorUInt8_clear(swigCPtr, this);
  }

  public ArrayofVectorUInt8(int count, VectorUInt8 value) {
    this(pirJNI.new_ArrayofVectorUInt8__SWIG_2(count, VectorUInt8.getCPtr(value), value), true);
  }

  private int doSize() {
    return pirJNI.ArrayofVectorUInt8_doSize(swigCPtr, this);
  }

  private void doAdd(VectorUInt8 x) {
    pirJNI.ArrayofVectorUInt8_doAdd__SWIG_0(swigCPtr, this, VectorUInt8.getCPtr(x), x);
  }

  private void doAdd(int index, VectorUInt8 x) {
    pirJNI.ArrayofVectorUInt8_doAdd__SWIG_1(swigCPtr, this, index, VectorUInt8.getCPtr(x), x);
  }

  private VectorUInt8 doRemove(int index) {
    return new VectorUInt8(pirJNI.ArrayofVectorUInt8_doRemove(swigCPtr, this, index), true);
  }

  private VectorUInt8 doGet(int index) {
    return new VectorUInt8(pirJNI.ArrayofVectorUInt8_doGet(swigCPtr, this, index), false);
  }

  private VectorUInt8 doSet(int index, VectorUInt8 val) {
    return new VectorUInt8(pirJNI.ArrayofVectorUInt8_doSet(swigCPtr, this, index, VectorUInt8.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    pirJNI.ArrayofVectorUInt8_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
