/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.pir;

public class pirJNI {
  public final static native long new_Faker();
  public final static native long Faker_GenerateCNIDCardNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateCNIDCardNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateTWCompatriotNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateTWCompatriotNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateTWIDCardNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateTWIDCardNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateTW2CNIDCardNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateTW2CNIDCardNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GeneratePhoneNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GeneratePhoneNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateMACAddress__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateMACAddress__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateIMEI__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateIMEI__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateIMSI__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateIMSI__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GenerateEmail__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GenerateEmail__SWIG_1(long jarg1, Faker jarg1_);
  public final static native long Faker_GeneratePassportNumber__SWIG_0(long jarg1, Faker jarg1_, int jarg2);
  public final static native long Faker_GeneratePassportNumber__SWIG_1(long jarg1, Faker jarg1_);
  public final static native void delete_Faker(long jarg1);
  public final static native long new_PirClient(int jarg1, long jarg2, VectorUInt8 jarg2_, boolean jarg3, long jarg4);
  public final static native void delete_PirClient(long jarg1);
  public final static native int PirClient_generate_data_query(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, int jarg3, long jarg4, ArrayofVectorUInt8 jarg4_);
  public final static native int PirClient_decrypt_data_reply(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, VectorUInt8 jarg3_);
  public final static native int PirClient_generate_data_query_with_count(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, int jarg3, long jarg4, ArrayofVectorUInt8 jarg4_);
  public final static native int PirClient_get_retrieved_indexes_and_ciphertext(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, ArrayofVectorUInt8 jarg3_, int jarg4, long jarg5, VectorUInt8 jarg5_, long jarg6, ArrayofVectorUInt8 jarg6_);
  public final static native int PirClient_generate_key_query_of_retrieved_indexes(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, VectorUInt8 jarg3_);
  public final static native int PirClient_decrypt_retrieved_ciphertext(long jarg1, PirClient jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, VectorUInt8 jarg3_, long jarg4, VectorUInt8 jarg4_);
  public final static native int PirClient_set_key(long jarg1, PirClient jarg1_, long jarg2, VectorUInt8 jarg2_);
  public final static native long PirClient_get_private_key(long jarg1, PirClient jarg1_);
  public final static native long PirClient_get_public_key(long jarg1, PirClient jarg1_);
  public final static native long new_PirServer(int jarg1, long jarg2, VectorUInt8 jarg2_, boolean jarg3, long jarg4);
  public final static native void delete_PirServer(long jarg1);
  public final static native int PirServer_generate_data_reply(long jarg1, PirServer jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, ArrayofVectorUInt8 jarg3_, long jarg4, ArrayofVectorUInt8 jarg4_, long jarg5, ArrayofVectorUInt8 jarg5_);
  public final static native int PirServer_generate_checked_data_reply(long jarg1, PirServer jarg1_, long jarg2, ArrayofVectorUInt8 jarg2_, long jarg3, ArrayofVectorUInt8 jarg3_, long jarg4, VectorUInt8 jarg4_, long jarg5, ArrayofVectorUInt8 jarg5_);
  public final static native int PirServer_generate_checked_key_reply(long jarg1, PirServer jarg1_, long jarg2, VectorUInt8 jarg2_, long jarg3, VectorUInt8 jarg3_, long jarg4);
  public final static native int PirServer_set_key(long jarg1, PirServer jarg1_, long jarg2, VectorUInt8 jarg2_);
  public final static native long PirServer_get_private_key(long jarg1, PirServer jarg1_);
  public final static native long PirServer_get_public_key(long jarg1, PirServer jarg1_);
  public final static native long new_VectorUInt8__SWIG_0();
  public final static native long new_VectorUInt8__SWIG_1(long jarg1, VectorUInt8 jarg1_);
  public final static native long VectorUInt8_capacity(long jarg1, VectorUInt8 jarg1_);
  public final static native void VectorUInt8_reserve(long jarg1, VectorUInt8 jarg1_, long jarg2);
  public final static native boolean VectorUInt8_isEmpty(long jarg1, VectorUInt8 jarg1_);
  public final static native void VectorUInt8_clear(long jarg1, VectorUInt8 jarg1_);
  public final static native long new_VectorUInt8__SWIG_2(int jarg1, short jarg2);
  public final static native int VectorUInt8_doSize(long jarg1, VectorUInt8 jarg1_);
  public final static native void VectorUInt8_doAdd__SWIG_0(long jarg1, VectorUInt8 jarg1_, short jarg2);
  public final static native void VectorUInt8_doAdd__SWIG_1(long jarg1, VectorUInt8 jarg1_, int jarg2, short jarg3);
  public final static native short VectorUInt8_doRemove(long jarg1, VectorUInt8 jarg1_, int jarg2);
  public final static native short VectorUInt8_doGet(long jarg1, VectorUInt8 jarg1_, int jarg2);
  public final static native short VectorUInt8_doSet(long jarg1, VectorUInt8 jarg1_, int jarg2, short jarg3);
  public final static native void VectorUInt8_doRemoveRange(long jarg1, VectorUInt8 jarg1_, int jarg2, int jarg3);
  public final static native void delete_VectorUInt8(long jarg1);
  public final static native long new_ArrayofVectorUInt8__SWIG_0();
  public final static native long new_ArrayofVectorUInt8__SWIG_1(long jarg1, ArrayofVectorUInt8 jarg1_);
  public final static native long ArrayofVectorUInt8_capacity(long jarg1, ArrayofVectorUInt8 jarg1_);
  public final static native void ArrayofVectorUInt8_reserve(long jarg1, ArrayofVectorUInt8 jarg1_, long jarg2);
  public final static native boolean ArrayofVectorUInt8_isEmpty(long jarg1, ArrayofVectorUInt8 jarg1_);
  public final static native void ArrayofVectorUInt8_clear(long jarg1, ArrayofVectorUInt8 jarg1_);
  public final static native long new_ArrayofVectorUInt8__SWIG_2(int jarg1, long jarg2, VectorUInt8 jarg2_);
  public final static native int ArrayofVectorUInt8_doSize(long jarg1, ArrayofVectorUInt8 jarg1_);
  public final static native void ArrayofVectorUInt8_doAdd__SWIG_0(long jarg1, ArrayofVectorUInt8 jarg1_, long jarg2, VectorUInt8 jarg2_);
  public final static native void ArrayofVectorUInt8_doAdd__SWIG_1(long jarg1, ArrayofVectorUInt8 jarg1_, int jarg2, long jarg3, VectorUInt8 jarg3_);
  public final static native long ArrayofVectorUInt8_doRemove(long jarg1, ArrayofVectorUInt8 jarg1_, int jarg2);
  public final static native long ArrayofVectorUInt8_doGet(long jarg1, ArrayofVectorUInt8 jarg1_, int jarg2);
  public final static native long ArrayofVectorUInt8_doSet(long jarg1, ArrayofVectorUInt8 jarg1_, int jarg2, long jarg3, VectorUInt8 jarg3_);
  public final static native void ArrayofVectorUInt8_doRemoveRange(long jarg1, ArrayofVectorUInt8 jarg1_, int jarg2, int jarg3);
  public final static native void delete_ArrayofVectorUInt8(long jarg1);
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
}
